-- Add geofencing fields to Business
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "geoLat" DOUBLE PRECISION;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "geoLng" DOUBLE PRECISION;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "geoRadius" INTEGER NOT NULL DEFAULT 200;

-- Add location capture to ClockEvent
ALTER TABLE "ClockEvent" ADD COLUMN IF NOT EXISTS "latitude" DOUBLE PRECISION;
ALTER TABLE "ClockEvent" ADD COLUMN IF NOT EXISTS "longitude" DOUBLE PRECISION;
